# Generated by Django 5.1.4 on 2025-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="product_moderator",
            field=models.BooleanField(default=False),
        ),
    ]
